name: Deploy to Vercel

on:
  push:
    branches:
      - dev
      - prod

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Vercel Deploy - Dev
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}

  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Vercel Deploy - Prod
        run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
